'use client';
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'sw' | 'pl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.sekela': 'Sekela APIS',
    'nav.developers': 'Developers',
    'nav.blog': 'Blog',
    'nav.customers': 'Customers',
    'nav.company': 'Company',
    'nav.contact_sales': 'Contact sales',
    'nav.start_building': 'Start building',
    'hero.title_part1': 'Grow Your Business.',
    'hero.title_part2': 'With Smart Technology.',
    'hero.description': 'We help organizations build tailored Systems, Webapps, Mobile Apps, Chatbots, and AI systems to solve the world’s hardest problems.',
    'page.products.title': 'Products',
    'page.products.desc': 'Practical AI and automation tools for modern business.',
    'page.solutions.title': 'Solutions',
    'page.solutions.desc': 'Practical technology solutions tailored to your real business needs.',
    'page.sekela.title': 'Sekela APIs',
    'page.sekela.desc': 'Simple and powerful APIs to automate your communication and operations.',
    'page.developers.title': 'Developers',
    'page.developers.desc': 'Everything you need to integrate our tools into your business.',
    'page.blog.title': 'Insights',
    'page.blog.desc': 'Latest news and simple guides on AI and automation.',
    'blog.latest_briefings': 'Latest Articles',
    'blog.read_all': 'Read all news',
    'blog.subscribe': 'Subscribe to our newsletter',
    'blog.subscribe_button': 'Join',
    'page.customers.title': 'Customers',
    'page.customers.desc': 'See how we help organizations automate and grow.',
    'page.company.title': 'Company',
    'page.company.desc': 'Our mission to enable African organizations through intelligent technology.',
    'page.models.title': 'Data & Insights',
    'page.models.desc': 'Turn your business data into clear plans for smarter decisions.',
    'company.founded': 'Founded',
    'company.founded_value': '2026',
    'company.headquarters': 'Headquarters',
    'company.headquarters_value': 'Dar es Salaam, Tanzania',
    'company.offices': 'Offices',
    'company.offices_value': 'Dar es Salaam • Dodoma',
    'dropdown.featured': 'Featured',
    'dropdown.categories': 'Categories',
    'dropdown.products.featured_title': 'Featured Products',
    'dropdown.products.title1': 'Sekela APIs',
    'dropdown.products.desc1': 'High-throughput APIs for SMS and USSD.',
    'dropdown.products.title2': 'Frontier Models',
    'dropdown.products.desc2': 'State-of-the-art ML models built for local languages.',
    'dropdown.products.read_all': 'View all products',
    'dropdown.products.cat_title': 'Product Suite',
    'dropdown.products.cat1': 'Custom SDKs',
    'dropdown.products.cat2': 'Applied AI',
    'dropdown.products.cat3': 'Cloud Orchestration',
    'dropdown.products.cat4': 'Infrastructure Audit',
    'dropdown.solutions.featured_title': 'Featured Solutions',
    'dropdown.solutions.title1': 'Practical AI & Automation',
    'dropdown.solutions.desc1': 'Reduce repetitive work with tailored AI copilots.',
    'dropdown.solutions.title2': 'Modern Infrastructure',
    'dropdown.solutions.desc2': 'DevOps and cloud migration for maximum uptime.',
    'dropdown.solutions.read_all': 'Explore solutions',
    'dropdown.solutions.cat_title': 'Industries & Needs',
    'dropdown.solutions.cat1': 'Digital Platforms',
    'dropdown.solutions.cat2': 'Security & Risk',
    'dropdown.solutions.cat3': 'Data & Analytics',
    'dropdown.solutions.cat4': 'Managed IT Support',
    'dropdown.sekela.featured_title': 'APIs and Gateways',
    'dropdown.sekela.title1': 'SMS Gateway',
    'dropdown.sekela.desc1': 'High-deliverability.',
    'dropdown.sekela.title2': 'Shamba API',
    'dropdown.sekela.desc2': 'Localized agricultural and weather alerts.',
    'dropdown.sekela.read_all': 'Read API Docs',
    'dropdown.sekela.cat_title': 'Our Gateways',
    'dropdown.sekela.cat1': 'USSD Menu',
    'dropdown.sekela.cat2': 'Chatbot APIs',
    'dropdown.developers.featured_title': 'Developer Resources',
    'dropdown.developers.title1': 'Launch Playground',
    'dropdown.developers.desc1': 'Interactive API sandbox for rapid development.',
    'dropdown.developers.title2': 'Webhooks & Events',
    'dropdown.developers.desc2': 'Real-time subscriptions for operational workflows.',
    'dropdown.developers.read_all': 'Visit Developer Portal',
    'dropdown.developers.cat_title': 'Tools & Docs',
    'dropdown.developers.cat1': 'API Reference',
    'dropdown.developers.cat2': 'SDK Libraries',
    'dropdown.developers.cat3': 'Data Schema',
    'dropdown.developers.cat4': 'UI Components',
    'dropdown.company.featured_title': 'About Antera',
    'dropdown.company.title1': 'Our Mission',
    'dropdown.company.desc1': 'Enabling African organizations with intelligent technology.',
    'dropdown.company.title2': 'Our Expertise',
    'dropdown.company.desc2': 'Expert engineering across cloud, AI, and security.',
    'dropdown.company.read_all': 'About us',
    'dropdown.company.cat_title': 'Explore Company',
    'dropdown.company.cat1': 'How We Work',
    'dropdown.company.cat2': 'Values',
    'dropdown.company.cat3': 'Join Us'
  },
  sw: {
    'nav.products': 'Bidhaa',
    'nav.solutions': 'Suluhisho',
    'nav.sekela': 'Sekela APIS',
    'nav.developers': 'Wanaendelezaji',
    'nav.blog': 'Blogu',
    'nav.customers': 'Wateja',
    'nav.company': 'Kampuni',
    'nav.contact_sales': 'Wasiliana na mauzo',
    'nav.start_building': 'Anza kujenga',
    'hero.title_part1': 'Rahisisha Kazi.',
    'hero.title_part2': 'Kua Haraka.',
    'hero.description': 'Tunatumia mifumo ya kisasa ya AI kurahisisha kazi zinazojirudia na kukuza biashara yako kwa usalama.',
    'page.products.title': 'Bidhaa',
    'page.products.desc': 'Zana rahisi za AI na mifumo ya kisasa kwa biashara.',
    'page.solutions.title': 'Suluhisho',
    'page.solutions.desc': 'Mifumo ya teknolojia inayolenga mahitaji halisi ya biashara yako.',
    'page.sekela.title': 'Sekela APIs',
    'page.sekela.desc': 'API rahisi na zenye nguvu kurahisisha mawasiliano na kazi zako.',
    'page.developers.title': 'Wanaendelezaji',
    'page.developers.desc': 'Kila kitu unachohitaji kuunganisha zana zetu kwenye biashara yako.',
    'page.blog.title': 'Makala',
    'page.blog.desc': 'Habari za hivi karibuni na miongozo rahisi kuhusu AI na teknolojia.',
    'blog.latest_briefings': 'Makala ya Karibuni',
    'blog.read_all': 'Soma habari zote',
    'blog.subscribe': 'Jiunge na jarida letu',
    'blog.subscribe_button': 'Jiunge',
    'page.customers.title': 'Wateja',
    'page.customers.desc': 'Ona jinsi tunavyosaidia mashirika kurahisisha kazi na kukua.',
    'page.company.title': 'Kampuni',
    'page.company.desc': 'Lengo letu ni kusaidia mashirika ya Afrika kupitia teknolojia ya kisasa.',
    'page.models.title': 'Akili ya Data',
    'page.models.desc': 'Badilisha data za biashara yako kuwa mipango madhubuti ya maamuzi bora.',
    'company.founded': 'Ilianzishwa',
    'company.founded_value': '2026',
    'company.headquarters': 'Makao Makuu',
    'company.headquarters_value': 'Dar es Salaam, Tanzania',
    'company.offices': 'Ofisi',
    'company.offices_value': 'Dar es Salaam • Dodoma',
    'dropdown.featured': 'Imeangaziwa',
    'dropdown.categories': 'Vipengele',
    'dropdown.products.featured_title': 'Bidhaa Zilizochaguliwa',
    'dropdown.products.title1': 'Sekela APIs',
    'dropdown.products.desc1': 'API zenye uwezo mkubwa kwa SMS na USSD',
    'dropdown.products.title2': 'Mifumo ya Frontier',
    'dropdown.products.desc2': 'Mifumo ya kisasa ya ML iliyoundwa kwa lugha za asili.',
    'dropdown.products.read_all': 'Tazama bidhaa zote',
    'dropdown.products.cat_title': 'Mfululizo wa Bidhaa',
    'dropdown.products.cat1': 'SDK Maalum',
    'dropdown.products.cat2': 'AI Inayotumika',
    'dropdown.products.cat3': 'Uratibu wa Wingu',
    'dropdown.products.cat4': 'Ukaguzi wa Miundombinu',
    'dropdown.solutions.featured_title': 'Suluhisho Zilizochaguliwa',
    'dropdown.solutions.title1': 'AI na Kazi Otomatiki',
    'dropdown.solutions.desc1': 'Punguza kazi zinazojirudia kwa kutumia wasaidizi wa AI.',
    'dropdown.solutions.title2': 'Miundombinu ya Kisasa',
    'dropdown.solutions.desc2': 'Uhamiaji wa wingu na DevOps kwa utendaji wa juu.',
    'dropdown.solutions.read_all': 'Gundua suluhisho',
    'dropdown.solutions.cat_title': 'Sekta na Mahitaji',
    'dropdown.solutions.cat1': 'Mifumo ya Kidijitali',
    'dropdown.solutions.cat2': 'Usalama na Hatari',
    'dropdown.solutions.cat3': 'Data na Uchambuzi',
    'dropdown.solutions.cat4': 'Msaada wa IT',
    'dropdown.sekela.featured_title': 'Mwangaza wa API',
    'dropdown.sekela.title1': 'Njia ya SMS',
    'dropdown.sekela.desc1': 'Uwasilishaji wa ujumbe wa kuaminika kwa shughuli zako.',
    'dropdown.sekela.title2': 'Shamba API',
    'dropdown.sekela.desc2': 'Arifa za kilimo na hali ya hewa za mahali hapo.',
    'dropdown.sekela.read_all': 'Soma Nyaraka za API',
    'dropdown.sekela.cat_title': 'Njia Zetu',
    'dropdown.sekela.cat1': 'Orodha ya USSD',
    'dropdown.sekela.cat2': 'API za Chatbot',
    'dropdown.developers.featured_title': 'Rasilimali za Wasanidi',
    'dropdown.developers.title1': 'Anzisha Playground',
    'dropdown.developers.desc1': 'Sehemu ya kujaribu API kwa maendeleo ya haraka.',
    'dropdown.developers.title2': 'Webhooks na Matukio',
    'dropdown.developers.desc2': 'Usajili wa matukio ya moja kwa moja ya kazi.',
    'dropdown.developers.read_all': 'Tembelea Jukwaa la Wasanidi',
    'dropdown.developers.cat_title': 'Zana na Nyaraka',
    'dropdown.developers.cat1': 'Mwongozo wa API',
    'dropdown.developers.cat2': 'Maktaba ya SDK',
    'dropdown.developers.cat3': 'Mfumo wa Data',
    'dropdown.developers.cat4': 'Vipengele vya UI',
    'dropdown.company.featured_title': 'Kuhusu Antera',
    'dropdown.company.title1': 'Lengo Letu',
    'dropdown.company.desc1': 'Kusaidia mashirika ya Afrika kupitia teknolojia ya kisasa.',
    'dropdown.company.title2': 'Ujuzi Wetu',
    'dropdown.company.desc2': 'Uhandisi wa kitaalamu katika wingu, AI na usalama.',
    'dropdown.company.read_all': 'Kuhusu sisi',
    'dropdown.company.cat_title': 'Chunguza Kampuni',
    'dropdown.company.cat1': 'Jinsi Tunavyofanya Kazi',
    'dropdown.company.cat2': 'Maadili Yetu',
    'dropdown.company.cat3': 'Jiunge Nasi'
  },
  pl: {
    'nav.products': 'Produkty',
    'nav.solutions': 'Rozwiązania',
    'nav.sekela': 'Sekela APIS',
    'nav.developers': 'Programiści',
    'nav.blog': 'Blog',
    'nav.customers': 'Klienci',
    'nav.company': 'Firma',
    'nav.contact_sales': 'Kontakt z handlowcem',
    'nav.start_building': 'Zacznij budować',
    'hero.title_part1': 'Automatyzuj Pracę.',
    'hero.title_part2': 'Skaluj Szybciej.',
    'hero.description': 'Wdrażamy praktyczne rozwiązania AI, które redukują powtarzalną pracę, zachowując bezpieczeństwo systemów.',
    'page.products.title': 'Produkty',
    'page.products.desc': 'Praktyczne narzędzia AI i automatyzacji dla nowoczesnego biznesu.',
    'page.solutions.title': 'Rozwiązania',
    'page.solutions.desc': 'Praktyczne rozwiązania technologiczne dostosowane do realnych potrzeb biznesowych.',
    'page.sekela.title': 'Sekela APIs',
    'page.sekela.desc': 'Proste i potężne interfejsy API do automatyzacji komunikacji i operacji.',
    'page.developers.title': 'Programiści',
    'page.developers.desc': 'Wszystko, czego potrzebujesz, aby zintegrować nasze narzędzia z Twoim biznesem.',
    'page.blog.title': 'Wnioski',
    'page.blog.desc': 'Najnowsze wiadomości i proste przewodniki po AI i automatyzacji.',
    'blog.latest_briefings': 'Najnowsze Artykuły',
    'blog.read_all': 'Przeczytaj wszystkie wiadomości',
    'blog.subscribe': 'Zapisz się do naszego newslettera',
    'blog.subscribe_button': 'Dołącz',
    'page.customers.title': 'Klienci',
    'page.customers.desc': 'Zobacz, jak pomagamy organizacjom automatyzować i rosnąć.',
    'page.company.title': 'Firma',
    'page.company.desc': 'Nasza misja wspierania afrykańskich organizacji poprzez inteligentną technologię.',
    'page.models.title': 'Inteligencja Danych',
    'page.models.desc': 'Zmień dane biznesowe w jasne plany dla mądrzejszych decyzji.',
    'company.founded': 'Założona',
    'company.founded_value': '2026',
    'company.headquarters': 'Siedziba Główna',
    'company.headquarters_value': 'Dar es Salaam, Tanzania',
    'company.offices': 'Biura',
    'company.offices_value': 'Dar es Salaam • Dodoma',
    'dropdown.featured': 'Wyróżnione',
    'dropdown.categories': 'Kategorie',
    'dropdown.products.featured_title': 'Wyróżnione Produkty',
    'dropdown.products.title1': 'Sekela APIs',
    'dropdown.products.desc1': 'Wydajne interfejsy API do SMS, USSD .',
    'dropdown.products.title2': 'Modele Frontier',
    'dropdown.products.desc2': 'Nowoczesne modele ML stworzone dla lokalnych języków.',
    'dropdown.products.read_all': 'Zobacz wszystkie produkty',
    'dropdown.products.cat_title': 'Pakiet Produktów',
    'dropdown.products.cat1': 'Dedykowane SDK',
    'dropdown.products.cat2': 'Zastosowanie AI',
    'dropdown.products.cat3': 'Orkiestracja Chmury',
    'dropdown.products.cat4': 'Audyt Infrastruktury',
    'dropdown.solutions.featured_title': 'Wyróżnione Rozwiązania',
    'dropdown.solutions.title1': 'Praktyczne AI i Automatyzacja',
    'dropdown.solutions.desc1': 'Zredukuj powtarzalną pracę dzięki asystentom AI.',
    'dropdown.solutions.title2': 'Nowoczesna Infrastruktura',
    'dropdown.solutions.desc2': 'DevOps i migracja do chmury dla maksymalnej stabilności.',
    'dropdown.solutions.read_all': 'Poznaj rozwiązania',
    'dropdown.solutions.cat_title': 'Branże i Potrzeby',
    'dropdown.solutions.cat1': 'Platformy Cyfrowe',
    'dropdown.solutions.cat2': 'Bezpieczeństwo i Ryzyko',
    'dropdown.solutions.cat3': 'Dane i Analityka',
    'dropdown.solutions.cat4': 'Wsparcie IT',
    'dropdown.sekela.featured_title': 'Wyróżnione API',
    'dropdown.sekela.title1': 'Bramka SMS',
    'dropdown.sekela.desc1': 'Niezawodne przesyłanie wiadomości dla Twoich operacji.',
    'dropdown.sekela.title2': 'Shamba API',
    'dropdown.sekela.desc2': 'Lokalne alerty rolnicze i pogodowe.',
    'dropdown.sekela.read_all': 'Przeczytaj Dokumentację API',
    'dropdown.sekela.cat_title': 'Nasze Bramki',
    'dropdown.sekela.cat1': 'Menu USSD',
    'dropdown.sekela.cat2': 'API Chatbotów',
    'dropdown.developers.featured_title': 'Zasoby dla Programistów',
    'dropdown.developers.title1': 'Uruchom Piaskownicę',
    'dropdown.developers.desc1': 'Interaktywne środowisko do testowania API.',
    'dropdown.developers.title2': 'Webhooks i Zdarzenia',
    'dropdown.developers.desc2': 'Subskrypcje zdarzeń w czasie rzeczywistym.',
    'dropdown.developers.read_all': 'Odwiedź Portal Programisty',
    'dropdown.developers.cat_title': 'Narzędzia i Dokumentacja',
    'dropdown.developers.cat1': 'Dokumentacja API',
    'dropdown.developers.cat2': 'Biblioteki SDK',
    'dropdown.developers.cat3': 'Schemat Danych',
    'dropdown.developers.cat4': 'Komponenty UI',
    'dropdown.company.featured_title': 'O Antera',
    'dropdown.company.title1': 'Nasza Misja',
    'dropdown.company.desc1': 'Wspieranie afrykańskich organizacji nowoczesną technologią.',
    'dropdown.company.title2': 'Nasza Wiedza',
    'dropdown.company.desc2': 'Ekspercka inżynieria w chmurze, AI i bezpieczeństwie.',
    'dropdown.company.read_all': 'O nas',
    'dropdown.company.cat_title': 'Poznaj Firmę',
    'dropdown.company.cat1': 'Jak Pracujemy',
    'dropdown.company.cat2': 'Nasze Wartości',
    'dropdown.company.cat3': 'Dołącz do Nas'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};