'use client';
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.sekela': 'Sekela Suite',
    'nav.developers': 'Developers',
    'nav.blog': 'Blog',
    'nav.customers': 'Customers',
    'nav.company': 'Company',
    'nav.contact_sales': 'Contact sales',
    'nav.start_building': 'Start building',
    'hero.title_part1': 'Grow Your Business.',
    'hero.title_part2': 'With Smart Technology.',
    'hero.description': 'We help organizations build tailored Systems, Webapps, Mobile Apps, Chatbots, and AI systems to solve the world’s hardest problems.',
    'page.products.title': 'Products',
    'page.products.desc': 'Practical AI and automation tools for modern business.',
    'page.solutions.title': 'Solutions',
    'page.solutions.desc': 'Practical technology solutions tailored to your real business needs.',
    'page.sekela.title': 'Sekela Suite',
    'page.sekela.desc': 'Simple and powerful platforms to automate your communication and operations.',
    'page.developers.title': 'Developers',
    'page.developers.desc': 'Everything you need to integrate our tools into your business.',
    'page.blog.title': 'Insights',
    'page.blog.desc': 'Latest news and simple guides on AI and automation.',
    'blog.latest_briefings': 'Latest Articles',
    'blog.read_all': 'Read all news',
    'blog.subscribe': 'Subscribe to our newsletter',
    'blog.subscribe_button': 'Join',
    'page.customers.title': 'Customers',
    'page.customers.desc': 'See how we help organizations automate and grow.',
    'page.company.title': 'Company',
    'page.company.desc': 'Our mission to enable African organizations through intelligent technology.',
    'page.models.title': 'Data & Insights',
    'page.models.desc': 'Turn your business data into clear plans for smarter decisions.',
    'company.founded': 'Founded',
    'company.founded_value': '2026',
    'company.headquarters': 'Headquarters',
    'company.headquarters_value': 'Dar es Salaam, Tanzania',
    'company.offices': 'Offices',
    'company.offices_value': 'Dar es Salaam • Dodoma',
    'dropdown.featured': 'Featured',
    'dropdown.categories': 'Categories',
    'dropdown.products.featured_title': 'Featured Products',
    'dropdown.products.title1': 'Sekela Suite',
    'dropdown.products.desc1': 'High-throughput platforms for SMS and USSD.',
    'dropdown.products.title2': 'Frontier Models',
    'dropdown.products.desc2': 'State-of-the-art ML models built for local languages.',
    'dropdown.products.read_all': 'View all products',
    'dropdown.products.cat_title': 'Product Suite',
    'dropdown.products.cat1': 'Custom SDKs',
    'dropdown.products.cat2': 'Applied AI',
    'dropdown.products.cat3': 'Cloud Orchestration',
    'dropdown.products.cat4': 'Infrastructure Audit',
    'dropdown.solutions.featured_title': 'Featured Solutions',
    'dropdown.solutions.title1': 'Practical AI & Automation',
    'dropdown.solutions.desc1': 'Reduce repetitive work with tailored AI copilots.',
    'dropdown.solutions.title2': 'Modern Infrastructure',
    'dropdown.solutions.desc2': 'DevOps and cloud migration for maximum uptime.',
    'dropdown.solutions.read_all': 'Explore solutions',
    'dropdown.solutions.cat_title': 'Industries & Needs',
    'dropdown.solutions.cat1': 'Digital Platforms',
    'dropdown.solutions.cat2': 'Security & Risk',
    'dropdown.solutions.cat3': 'Data & Analytics',
    'dropdown.solutions.cat4': 'Managed IT Support',
    'dropdown.sekela.featured_title': 'Platforms and Gateways',
    'dropdown.sekela.title1': 'SMS Gateway',
    'dropdown.sekela.desc1': 'High-deliverability.',
    'dropdown.sekela.title2': 'Shamba Suite',
    'dropdown.sekela.desc2': 'Localized agricultural and weather alerts.',
    'dropdown.sekela.read_all': 'Read Docs',
    'dropdown.sekela.cat_title': 'Our Gateways',
    'dropdown.sekela.cat1': 'USSD Menu',
    'dropdown.sekela.cat2': 'Chatbot Integration',
    'dropdown.developers.featured_title': 'Developer Resources',
    'dropdown.developers.title1': 'Launch Playground',
    'dropdown.developers.desc1': 'Interactive sandbox for rapid development.',
    'dropdown.developers.title2': 'Webhooks & Events',
    'dropdown.developers.desc2': 'Real-time subscriptions for operational workflows.',
    'dropdown.developers.read_all': 'Visit Developer Portal',
    'dropdown.developers.cat_title': 'Tools & Docs',
    'dropdown.developers.cat1': 'Documentation',
    'dropdown.developers.cat2': 'SDK Libraries',
    'dropdown.developers.cat3': 'Data Schema',
    'dropdown.developers.cat4': 'UI Components',
    'dropdown.company.featured_title': 'About Antera',
    'dropdown.company.title1': 'Our Mission',
    'dropdown.company.desc1': 'Enabling African organizations with intelligent technology.',
    'dropdown.company.title2': 'Our Expertise',
    'dropdown.company.desc2': 'Expert engineering across cloud, AI, and security.',
    'dropdown.company.read_all': 'About us',
    'dropdown.company.cat_title': 'Explore Company',
    'dropdown.company.cat1': 'How We Work',
    'dropdown.company.cat2': 'Values',
    'dropdown.company.cat3': 'Join Us'
  },
  sw: {
    'nav.products': 'Bidhaa',
    'nav.solutions': 'Suluhisho',
    'nav.sekela': 'Sekela Suite',
    'nav.developers': 'Wanaendelezaji',
    'nav.blog': 'Blogu',
    'nav.customers': 'Wateja',
    'nav.company': 'Kampuni',
    'nav.contact_sales': 'Wasiliana na mauzo',
    'nav.start_building': 'Anza kujenga',
    'hero.title_part1': 'Rahisisha Kazi.',
    'hero.title_part2': 'Kua Haraka.',
    'hero.description': 'Tunatumia mifumo ya kisasa ya AI kurahisisha kazi zinazojirudia na kukuza biashara yako kwa usalama.',
    'page.products.title': 'Bidhaa',
    'page.products.desc': 'Zana rahisi za AI na mifumo ya kisasa kwa biashara.',
    'page.solutions.title': 'Suluhisho',
    'page.solutions.desc': 'Mifumo ya teknolojia inayolenga mahitaji halisi ya biashara yako.',
    'page.sekela.title': 'Sekela Suite',
    'page.sekela.desc': 'Mifumo rahisi na yenye nguvu kurahisisha mawasiliano na kazi zako.',
    'page.developers.title': 'Wanaendelezaji',
    'page.developers.desc': 'Kila kitu unachohitaji kuunganisha zana zetu kwenye biashara yako.',
    'page.blog.title': 'Makala',
    'page.blog.desc': 'Habari za hivi karibuni na miongozo rahisi kuhusu AI na teknolojia.',
    'blog.latest_briefings': 'Makala ya Karibuni',
    'blog.read_all': 'Soma habari zote',
    'blog.subscribe': 'Jiunge na jarida letu',
    'blog.subscribe_button': 'Jiunge',
    'page.customers.title': 'Wateja',
    'page.customers.desc': 'Ona jinsi tunavyosaidiaz mashirika kurahisisha kazi na kukua.',
    'page.company.title': 'Kampuni',
    'page.company.desc': 'Lengo letu ni kusaidia mashirika ya Afrika kupitia teknolojia ya kisasa.',
    'page.models.title': 'Akili ya Data',
    'page.models.desc': 'Badilisha data za biashara yako kuwa mipango madhubuti ya maamuzi bora.',
    'company.founded': 'Ilianzishwa',
    'company.founded_value': '2026',
    'company.headquarters': 'Makao Makuu',
    'company.headquarters_value': 'Dar es Salaam, Tanzania',
    'company.offices': 'Ofisi',
    'company.offices_value': 'Dar es Salaam • Dodoma',
    'dropdown.featured': 'Imeangaziwa',
    'dropdown.categories': 'Vipengele',
    'dropdown.products.featured_title': 'Bidhaa Zilizochaguliwa',
    'dropdown.products.title1': 'Sekela Suite',
    'dropdown.products.desc1': 'Mifumo yenye uwezo mkubwa kwa SMS na USSD',
    'dropdown.products.title2': 'Mifumo ya Frontier',
    'dropdown.products.desc2': 'Mifumo ya kisasa ya ML iliyoundwa kwa lugha za asili.',
    'dropdown.products.read_all': 'Tazama bidhaa zote',
    'dropdown.products.cat_title': 'Mfululizo wa Bidhaa',
    'dropdown.products.cat1': 'SDK Maalum',
    'dropdown.products.cat2': 'AI Inayotumika',
    'dropdown.products.cat3': 'Uratibu wa Wingu',
    'dropdown.products.cat4': 'Ukaguzi wa Miundombinu',
    'dropdown.solutions.featured_title': 'Suluhisho Zilizochaguliwa',
    'dropdown.solutions.title1': 'AI na Kazi Otomatiki',
    'dropdown.solutions.desc1': 'Punguza kazi zinazojirudia kwa kutumia wasaidizi wa AI.',
    'dropdown.solutions.title2': 'Miundombinu ya Kisasa',
    'dropdown.solutions.desc2': 'Uhamiaji wa wingu na DevOps kwa utendaji wa juu.',
    'dropdown.solutions.read_all': 'Gundua suluhisho',
    'dropdown.solutions.cat_title': 'Sekta na Mahitaji',
    'dropdown.solutions.cat1': 'Mifumo ya Kidijitali',
    'dropdown.solutions.cat2': 'Usalama na Hatari',
    'dropdown.solutions.cat3': 'Data na Uchambuzi',
    'dropdown.solutions.cat4': 'Msaada wa IT',
    'dropdown.sekela.featured_title': 'Mwangaza wa Mfumo',
    'dropdown.sekela.title1': 'Njia ya SMS',
    'dropdown.sekela.desc1': 'Uwasilishaji wa ujumbe wa kuaminika kwa shughuli zako.',
    'dropdown.sekela.title2': 'Shamba Suite',
    'dropdown.sekela.desc2': 'Arifa za kilimo na hali ya hewa za mahali hapo.',
    'dropdown.sekela.read_all': 'Soma Nyaraka',
    'dropdown.sekela.cat_title': 'Njia Zetu',
    'dropdown.sekela.cat1': 'Orodha ya USSD',
    'dropdown.sekela.cat2': 'Mifumo ya Chatbot',
    'dropdown.developers.featured_title': 'Rasilimali za Wasanidi',
    'dropdown.developers.title1': 'Anzisha Playground',
    'dropdown.developers.desc1': 'Sehemu ya kujaribu mifumo kwa maendeleo ya haraka.',
    'dropdown.developers.title2': 'Webhooks na Matukio',
    'dropdown.developers.desc2': 'Usajili wa matukio ya moja kwa moja ya kazi.',
    'dropdown.developers.read_all': 'Tembelea Jukwaa la Wasanidi',
    'dropdown.developers.cat_title': 'Zana na Nyaraka',
    'dropdown.developers.cat1': 'Mwongozo wa Documentation',
    'dropdown.developers.cat2': 'Maktaba ya SDK',
    'dropdown.developers.cat3': 'Mfumo wa Data',
    'dropdown.developers.cat4': 'Vipengele vya UI',
    'dropdown.company.featured_title': 'Kuhusu Antera',
    'dropdown.company.title1': 'Lengo Letu',
    'dropdown.company.desc1': 'Kusaidia mashirika ya Afrika kupitia teknolojia ya kisasa.',
    'dropdown.company.title2': 'Ujuzi Wetu',
    'dropdown.company.desc2': 'Uhandisi wa kitaalamu katika wingu, AI na usalama.',
    'dropdown.company.read_all': 'Kuhusu sisi',
    'dropdown.company.cat_title': 'Chunguza Kampuni',
    'dropdown.company.cat1': 'Jinsi Tunavyofanya Kazi',
    'dropdown.company.cat2': 'Maadili Yetu',
    'dropdown.company.cat3': 'Jiunge Nasi'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};